---
language: node_js
node_js:
  - "4.2.1"

sudo: false

cache:
  directories:
    - node_modules
    - front-end/node_modules
    - front-end/bower_components
    - front-end/persistent-filter-caches

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g -q bower"
  - "npm --version"
  - "bower --version"
  - "phantomjs --version"

script:
  - cd front-end/ && bower install --allow-root && npm install && ember test
